title: barrettjflowers
description: Personal site and digital garden
url: "https://barrettjflowers.dev"
baseurl: ""
markdown: kramdown
permalink: pretty

defaults:
  - scope:
      path: "blog"
    values:
      layout: default

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

include:
  - .well-known

exclude:
  - README.MD
  - CNAME
